In [1]:
import numpy as np

### Given an incompressible fluid flowing through a short section of horizontal pipe, write a function to calculate the outlet pressure if the inlet pressure, inlet velocity, and outlet velocity are known.

\begin{align}
\ P_(inlet) + \frac{p  (v_(in))^2}{2}  & = P_(outlet) + \frac{p  (v_(out))^2}{2}
\end{align}

In [2]:
def get_pressure(inlet_P, inlet_vel, outlet_vel):
    #Assuming the fluid is water which has a density of 1000 Kg/m3
    return inlet_P + 500*((inlet_vel**2)-(outlet_vel**2))

### Write a function to calculate the pressure drop in a pipe given the flow velocity, density, viscosity, and pipe diameter, and pipe length, assuming the Reynold’s number is less than 2300.

\begin{align}
\ p  & =  \frac{32 u L v}{\pi d^2}
\end{align}

In [3]:
def pressure_drop(velocity, density, viscosity, diameter, length):
    return 32*viscosity*length*velocity/ (np.pi * (diameter**2))
    

### Given the differential equation
### f'(x) = x^x,
### write a function that uses Euler's method to approximate the value of f(x1) given an initial condition (x0, f(x0)) and the value of x1. 

In [4]:

def d_eq(x):
    return x**x

def solve_eq(x_in, x_end, y_in, n_steps = 1000):
    x_vals = np.linspace(x_in, x_end, n_steps)
    d_x = (x_end - x_in)/(n_steps - 1.0)
    d_y = [d_eq(x)*d_x for x in x_vals] #since the function is not y dependent
    return y_in + sum(d_y)

solve_eq(0, 1, 0) #If you want to from 0 to 1 and y_in is 0

0.784432337437171

#### Given a string representing a Roman numeral, write a function to compute the Arabic numerical equivalent. For example `roman_to_arabic("MDCCLXXVI")` should return `1776`. 

In [5]:
def roman_to_arabic(rom_num):
    rom_dic = {'I':1, 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}
    num = 0
    for s in rom_num:
        num += rom_dic[s]
    return num

roman_to_arabic("MDCCLXXVI")

1776

####  Write a generic function to compute various scenarios for the following optimization problem: A farmer owns X acres of land. She profits P1 dollars per acre of corn and P2 dollars per acre of oats. Her team has Y hours of labor available. The corn takes H1
#### hours of labor per acre and oats require H2 hours of labor per acre. How many acres of each can be planted to maximize profits?
#### Test
#### the function for the following cases:
#### a)
#### X = 240, Y = 320, P1 = $40, P2 = $30, H1 = 2, H2 = 1
#### b)
#### X = 300, Y = 380, P1 = $70, P2 = $45, H1 = 3, H2 = 1
#### c)
####  X = 180, Y = 420, P1 = $65, P2 = $55, H1 = 3, H2 = 2 

In [6]:
def acres(X, Y, P1, P2, H1, H2):
    C = np.array([[P1/H1], [P2/H2]]) #Set up equation
    intersection = ((Y - X*H1)*(Y - X*H2)) < 0  #see if there is a linear interception
    m = np.array([[0, min(Y, X*H2)], [min(Y, X*H1), 0]]) #set up matrix with extreme values
    if intersection:
        d = np.array([[1.0, 1.0], [1.0/H1, 1.0/H2]])
        r = np.matmul(np.linalg.inv(d), np.array([[Y], [X]])) #intersection coordinates
        m = np.append(r, m).reshape(-1, 2) #append to matrix
    res = np.matmul(m, C) #check the value of the 3 extreme values
    return np.append(m[np.argmax(res)] * d[1], max(res)) #return the values that give the largest profit
    

In [7]:
X = 240
Y = 320
P1 = 40
P2= 30
H1 = 2
H2 = 1
acres(X, Y, P1, P2, H1, H2) #80 of corn and 160 of oats, 8000$ profit

array([  80.,  160., 8000.])

In [8]:
X = 300
Y = 380
P1 = 70
P2= 45
H1 = 3
H2 = 1
acres(X, Y, P1, P2, H1, H2) #40 of corn and 260 of oats, 14460$ profit

array([   40.,   260., 14460.])

In [9]:
X = 180
Y = 420
P1 = 65
P2= 55
H1 = 3
H2 = 2
acres(X, Y, P1, P2, H1, H2) #60 of corn and 120 of oats, 10260$ profit

array([   60.,   120., 10260.])